package org.mybatis.spring.datasource.dao;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.cache.CacheVersion;
import org.mybatis.spring.datasource.DataSourceContextHolder;
import org.mybatis.spring.datasource.pojo.StatKopInfo;

import com.linda.common.mybatis.generator.annotation.Table;

/**
 * @author AutoGenerated by lindzh
 * 2016年07月21日 11:21
 */
@CacheVersion("v1.0")
@Table(name="koa_req_stat",datasource=DataSourceContextHolder.DATA_SOURCE_STAT)
//选择数据源
public interface StatKopInfoDao {
	
	public int addStatKopInfo(StatKopInfo obj);
	
	public StatKopInfo getById(@Param("id")long id);
	
	public int updateById(@Param("obj")StatKopInfo obj);
	
	public int deleteById(@Param("id")long id);
	
}
